import type { Metadata } from 'next';
import { Source_Sans_3 } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';

const source = Source_Sans_3({
  weight: '400',
  style: 'normal',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Hub Radar',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={source.className}>
        <ThemeProvider attribute="class" defaultTheme="sytem" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
